language: go

go:
  - 1.13.x

go_import_path: github.com/vusalalishov/api-tester

install:
  - go get -v github.com/codeclimate/test-reporter

before_script:
  - test-reporter before-build
script:
  - go test -coverprofile c.out github.com/vusalalishov/api-tester/...
after_script:
  - test-reporter after-build --coverage-input-type gocov --exit-code $TRAVIS_TEST_RESULT

notifications:
  email:
    recipients:
      - vusal.alishov@gmail.com
    on_success: never
    on_failure: always