language: go

go:
  - 1.13.x

go_import_path: github.com/vusalalishov/api-tester

before_install:
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

script:
  - go test -v github.com/vusalalishov/api-tester/... -coverprofile=all.coverptofile
  - gover
  - goveralls -coverprofile gover.coverprofile -service travis-ci

notifications:
  email:
    recipients:
      - vusal.alishov@gmail.com
    on_success: never
    on_failure: always